#################################
#             Shadows           #
#################################
shadow = true;
shadow-radius = 50;
shadow-opacity = 0.85;
shadow-offset-x = -50;
shadow-offset-y = -50;
shadow-color = "#ff007b";
crop-shadow-to-monitor = true;
unredir-if-possible = false;

#################################
#            Blur               #
#################################
blur:
{
  method = "box";
  size = 20;
};
#################################
#       General Settings        #
#################################
backend = "xrender";
vsync = true;
xrender-sync-fence = true;
detect-rounded-corners = true;
detect-transient = true;
detect-client-leader = false;
# log-level = "warn";
corner-radius = 10;
#################################
#       Window rules            #
#################################
rules: ({
  match = "window_type = 'tooltip'";
  shadow = true;
  full-shadow = false;
}, {
  match = "_GTK_FRAME_EXTENTS@";
  blur-background = false;
  shadow = false;
}, {
  match = "class_g = 'i3bar'    || "
          "class_g = 'i3-frame'    || "
          "window_type = 'dialog' || "
          "window_type = 'menu' || "
          "window_type = 'toolbar' || "
          "window_type = 'dropdown_menu' || "
          "window_type = 'popup_menu' || "
          "window_type = 'notification'";
  blur-background = false;
  corner-radius = 0;
  opacity = 1.0;
  shadow = false;
}, {
  match = "window_type = 'toolbar'    || "
          "window_type = 'dialog' || "
          "window_type = 'menu' || "
          "class_g *?= 'transformice' || "
          "class_g *?= 'i3bar'";
  corner-radius = 0;
}, {
  match = "_GTK_FRAME_EXTENTS@";
  shadow = false;
}, {
  match = "class_g = 'conky'	|| "
	  "class_g = 'Dunst'";
  opacity = 0.7;
  blur-background = false;
}, {
  match = "class_g *?= 'kitty'";
  opacity = 0.69;
  blur-background = true;
  detect-transient = true;
}, {
  match = "class_g = 'qutebrowser'    || "
          "class_g *?= 'transformice'"; 
  opacity = 1.0; 
})
